### PR TITLE
Fix CSS of Divide XP selector width

### PR DESCRIPTION
**Pull request by hmqgg**

### CODE REVIEW

**Comment by ironmonk88** [comment]
Honestly, this should probably be in Little Details as a system-wide css change.  It's interesting that the text boxes have this width limitation but the select doesn't.  I'm kind of concerned about the effects such a broad change might make though.

I did change the English text to be short enough to fit, but I like the idea of ensuring the select box stays the same as the input boxes.

**Comment by hmqgg** [comment]
Yep, short description makes it look better.

**Comment by hmqgg** [comment]
I'll close it as for now.

**Comment by ironmonk88** [comment]
This should actually be live with the Little Details module now.  Just hadn't gotten around to updates yet.  :-)
In the end I figured it would work better over there.

**Pull request closed without merging**
